/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-15 07:31:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1745564305677L));
    _jspx_dependants.put("jar:file:/D:/midproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tripin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Pacifico 폰트 링크 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Pacifico&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Noto Sans KR 폰트 링크 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Remix icon 아이콘 폰트 라이브러리 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.6.0/remixicon.min.css\">\r\n");
      out.write("<!-- 내 css 파일경로 -->\r\n");
      out.write("<link href=\"resources/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- 내 js 파일경로 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/mypage.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--     <header class=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a href=\"#\" class=\"logo\">Tripin</a>\r\n");
      out.write("            <div class=\"flex items-center space-x-4\">\r\n");
      out.write("                <div class=\"w-8 h-8 flex items-center justify-center\">\r\n");
      out.write("                    <i class=\"ri-notification-3-line text-gray-600\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"w-8 h-8 flex items-center justify-center\">\r\n");
      out.write("                    <i class=\"ri-settings-3-line text-gray-600\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 헤더 -->\r\n");
      out.write("  <header class=\"place_list_header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <!-- 타이틀 -->\r\n");
      out.write("      <div class=\"left-header\">\r\n");
      out.write("	      <a href=\"#\" class=\"main_title\">Tripin</a> \r\n");
      out.write("	      <nav class=\"main-nav\">\r\n");
      out.write("	      	<a href=\"#\" class=\"home\">홈</a>\r\n");
      out.write("	      	<a href=\"#\" class=\"trivy\">트리비와 대화하기</a>\r\n");
      out.write("	      	<a href=\"#\" class=\"theme\">테마여행</a>      \r\n");
      out.write("	      </nav>	\r\n");
      out.write("      </div>\r\n");
      out.write("    <div class=\"icon-group\">\r\n");
      out.write("      <button class=\"icon-button\">\r\n");
      out.write("        <i class=\"ri-user-line\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <main class=\"container mx-auto px-4 py-6\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <!-- 프로필 섹션 -->\r\n");
      out.write("        <section class=\"profile-section\">\r\n");
      out.write("            <div class=\"profile-container\">\r\n");
      out.write("                <div class=\"profile-image-wrapper\">\r\n");
      out.write("                    <div class=\"profile-image-box\">\r\n");
      out.write("                        <img src=\"https://readdy.ai/api/search-image?query=portrait%20of%20a%20young%20Korean%20woman%20with%20short%20hair%2C%20soft%20lighting%2C%20minimalist%20background%2C%20professional%20headshot%20style&amp;width=200&amp;height=200&amp;seq=1&amp;orientation=squarish\" alt=\"프로필 이미지\" class=\"w-full h-full object-cover\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button id=\"edit-profile-photo-btn\" class=\"edit-button\">\r\n");
      out.write("                        <i class=\"ri-pencil-line\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"profile-text\">\r\n");
      out.write("                    <h1 id=\"profile-name\" class=\"profile-name\">김지연</h1>\r\n");
      out.write("                    <p id=\"profile-email\" class=\"profile-email\">jiyeon.kim@example.com</p>\r\n");
      out.write("                    <div class=\"profile-tags\">\r\n");
      out.write("                        <span class=\"tag blue\">여행 애호가</span>\r\n");
      out.write("                        <span class=\"tag green\">리뷰 10개</span>\r\n");
      out.write("                        <span class=\"tag purple\">VIP 회원</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button id=\"edit-profile-btn\" class=\"edit-profile-btn\">\r\n");
      out.write("                    프로필 편집\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- 탭 네비게이션 -->\r\n");
      out.write("        <div class=\"tab-section\">\r\n");
      out.write("            <div class=\"tab-header\">\r\n");
      out.write("                <button class=\"tab-button\" id=\"place-saved\">저장한 여행지</button>\r\n");
      out.write("                <button class=\"tab-button\" id=\"themes-saved\">저장한 테마</button>\r\n");
      out.write("                <button class=\"tab-button\" id=\"review-written\">내가 작성한 리뷰</button>\r\n");
      out.write("                 \r\n");
      out.write("            </div>\r\n");
      out.write("			\r\n");
      out.write("            <!-- 저장 콘텐츠 탭 컨텐츠 -->\r\n");
      out.write("            <div id=\"content-saved\" class=\"p-6\">                \r\n");
      out.write("\r\n");
      out.write("                <!-- 저장한 여행지 탭 -->\r\n");
      out.write("                <div id=\"content-places\" class=\"content-hidden\">\r\n");
      out.write("                    <div class=\"places-grid\">\r\n");
      out.write("                        <!-- 저장한 여행지 1 -->\r\n");
      out.write("                        <div class=\"place-card\">\r\n");
      out.write("                            <div class=\"place-image-wrapper\">\r\n");
      out.write("                                <img src=\"https://readdy.ai/api/search-image?query=beautiful%20landscape%20of%20Seoraksan%20National%20Park%2C%20South%20Korea%2C%20mountain%20peaks%2C%20autumn%20colors%2C%20hiking%20trails%2C%20travel%20destination&amp;width=400&amp;height=200&amp;seq=6&amp;orientation=landscape\" alt=\"설악산\" class=\"w-full h-full object-cover object-top\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"place-info\">\r\n");
      out.write("                                <h3 id=\"place-title\" class=\"place-title\">설악산 국립공원</h3>\r\n");
      out.write("                                <p id=\"place-location\" class=\"place-location\">강원도 속초시</p>\r\n");
      out.write("                                <div class=\"place-rating\">\r\n");
      out.write("                                    <div class=\"stars\">\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-half-fill\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span id=\"review-avg\" class=\"review-text\">4.5 (120 리뷰)</span>\r\n");
      out.write("                                    <span id=\"review-count\" class=\"review-text\">(120 리뷰)</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"place-actions\">\r\n");
      out.write("                                    <button class=\"detail-button\">\r\n");
      out.write("                                        <i class=\"ri-information-line mr-1\"></i> 상세정보\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button class=\"heart-button\">\r\n");
      out.write("                                        <i class=\"ri-heart-fill\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        <!-- 저장한 여행지 2 -->\r\n");
      out.write("                        <div class=\"place-card\">\r\n");
      out.write("                            <div class=\"place-image-wrapper\">\r\n");
      out.write("                                <img src=\"https://readdy.ai/api/search-image?query=beautiful%20beach%20of%20Jungmun%20in%20Jeju%20Island%2C%20South%20Korea%2C%20with%20volcanic%20rocks%2C%20clear%20blue%20water%2C%20sandy%20shore%2C%20travel%20destination&amp;width=400&amp;height=200&amp;seq=7&amp;orientation=landscape\" alt=\"중문해변\" class=\"w-full h-full object-cover object-top\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"place-info\">\r\n");
      out.write("                                <h3 class=\"place-title\">중문 해변</h3>\r\n");
      out.write("                                <p class=\"place-location\">제주도 서귀포시</p>\r\n");
      out.write("                                <div class=\"place-rating\">\r\n");
      out.write("                                    <div class=\"stars\">\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        <i class=\"ri-star-line\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span id=\"review-avg\" class=\"review-text\">4.0</span>\r\n");
      out.write("                                    <span id=\"review-count\" class=\"review-text\">(85 리뷰)</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"place-actions\">\r\n");
      out.write("                                    <button class=\"detail-button\">\r\n");
      out.write("                                        <i class=\"ri-information-line mr-1\"></i> 상세정보\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button class=\"heart-button\">\r\n");
      out.write("                                        <i class=\"ri-heart-fill\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 저장한 테마 탭 컨텐츠 -->\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"content-themes\" class=\"content-hidden\">\r\n");
      out.write("                    <div class=\"themes-grid\">\r\n");
      out.write("                        <!-- 저장한 테마 1 -->\r\n");
      out.write("                        <div class=\"theme-card\">\r\n");
      out.write("                            <div class=\"theme-image-wrapper\">\r\n");
      out.write("                                <img src=\"https://readdy.ai/api/search-image?query=Korean%20traditional%20food%20assortment%2C%20bibimbap%2C%20kimchi%2C%20bulgogi%2C%20colorful%20side%20dishes%2C%20authentic%20Korean%20cuisine%2C%20travel%20food%20experience&amp;width=400&amp;height=200&amp;seq=9&amp;orientation=landscape\" alt=\"한식 체험\" class=\"w-full h-full object-cover object-top\">\r\n");
      out.write("                                <div class=\"image-overlay\">\r\n");
      out.write("                                    <h3 class=\"overlay-title\">한식 체험 여행</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"theme-content\">\r\n");
      out.write("                                <p class=\"theme-description\">전통 한식부터 현대적 퓨전 요리까지, 한국의 맛을 탐험하는 여행</p>\r\n");
      out.write("                                <div class=\"theme-footer\">\r\n");
      out.write("                                    <span class=\"theme-count\">10개 장소</span>\r\n");
      out.write("                                    <button class=\"bookmark-button\">\r\n");
      out.write("                                        <i class=\"ri-bookmark-fill\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("				<!-- 내가 작성한 리뷰 탭 컨텐츠 -->\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"content-reviews\" class=\"content-hidden\">\r\n");
      out.write("                    <div class=\"review-list\">\r\n");
      out.write("                        <!-- 리뷰 1 -->\r\n");
      out.write("                        <div class=\"review-card\">\r\n");
      out.write("                            <div class=\"review-header\">\r\n");
      out.write("                                <div class=\"review-place\">\r\n");
      out.write("                                    <div class=\"review-avatar\">\r\n");
      out.write("                                        <img src=\"https://readdy.ai/api/search-image?query=beautiful%20landscape%20of%20Gyeongbokgung%20Palace%2C%20Seoul%2C%20South%20Korea%2C%20traditional%20Korean%20architecture%2C%20palace%20grounds%2C%20travel%20destination&amp;width=100&amp;height=100&amp;seq=12&amp;orientation=squarish\" alt=\"경복궁\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h3 class=\"place-title\">경복궁</h3>\r\n");
      out.write("                                        <div class=\"star-rating\">\r\n");
      out.write("                                            <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                            <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                            <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                            <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                            <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"review-text\">2025.04.12</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"review-text\">한국의 역사와 문화를 느낄 수 있는 아름다운 궁궐이었습니다. 특히 수문장 교대식이 인상적이었고, 한복을 입고 방문하니 더욱 특별한 경험이 되었습니다. 계절마다 다른 모습을 보여준다고 하니 다음에는 가을에 방문해보고 싶습니다.</p>\r\n");
      out.write("                            <div class=\"review-photos\">\r\n");
      out.write("                                <div class=\"photo-thumbnail\">\r\n");
      out.write("                                    <img src=\"https://readdy.ai/api/search-image?query=detailed%20view%20of%20Gyeongbokgung%20Palace%20gate%2C%20traditional%20Korean%20architecture%2C%20tourists%20in%20hanbok%2C%20sunny%20day%2C%20travel%20photo&amp;width=100&amp;height=100&amp;seq=13&amp;orientation=squarish\" alt=\"리뷰 사진\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"photo-thumbnail\">\r\n");
      out.write("                                    <img src=\"https://readdy.ai/api/search-image?query=inside%20Gyeongbokgung%20Palace%2C%20traditional%20Korean%20pavilion%2C%20pond%2C%20mountains%20in%20background%2C%20beautiful%20scenery%2C%20travel%20photo&amp;width=100&amp;height=100&amp;seq=14&amp;orientation=squarish\" alt=\"리뷰 사진\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"review-actions\">\r\n");
      out.write("                                <button class=\"action-button update\">\r\n");
      out.write("                                    <i class=\"ri-edit-line mr-1\"></i> 수정\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"action-button delete\">\r\n");
      out.write("                                    <i class=\"ri-delete-bin-line mr-1\"></i> 삭제\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"custom-footer\">\r\n");
      out.write("        <div class=\"footer-container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-left\">\r\n");
      out.write("                    <p class=\"footer-text\">© 2025 Tripin. 모든 권리 보유.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-links\">\r\n");
      out.write("                    <a href=\"#\">고객센터</a>\r\n");
      out.write("                    <a href=\"#\">개인정보 처리방침</a>\r\n");
      out.write("                    <a href=\"#\">이용약관</a>\r\n");
      out.write("                    <a href=\"#\">로그아웃</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("<!--     <script type=\"text/javascript\" crossorigin=\"anonymous\" src=\"https://us-assets.i.posthog.com/array/phc_t9tkQZJiyi2ps9zUYm8TDsL6qXo4YmZx0Ot5rBlAlEd/config.js\"></script><script type=\"text/javascript\" crossorigin=\"anonymous\" src=\"https://us-assets.i.posthog.com/static/dead-clicks-autocapture.js?v=1.242.0\"></script><script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // 메인 탭 전환\r\n");
      out.write("            const mainTabs = {\r\n");
      out.write("                'tab-schedule': 'content-schedule',\r\n");
      out.write("                'tab-saved': 'content-saved',\r\n");
      out.write("                'tab-payment': 'content-payment'\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            Object.keys(mainTabs).forEach(tabId => {\r\n");
      out.write("                document.getElementById(tabId).addEventListener('click', function() {\r\n");
      out.write("                    // 모든 탭 비활성화\r\n");
      out.write("                    Object.keys(mainTabs).forEach(id => {\r\n");
      out.write("                        document.getElementById(id).classList.remove('tab-active');\r\n");
      out.write("                        document.getElementById(id).classList.add('text-gray-500');\r\n");
      out.write("                        document.getElementById(mainTabs[id]).classList.add('hidden');\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    // 선택한 탭 활성화\r\n");
      out.write("                    this.classList.add('tab-active');\r\n");
      out.write("                    this.classList.remove('text-gray-500');\r\n");
      out.write("                    document.getElementById(mainTabs[tabId]).classList.remove('hidden');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // 서브 탭 전환\r\n");
      out.write("            const subTabs = {\r\n");
      out.write("                'subtab-places': 'content-places',\r\n");
      out.write("                'subtab-themes': 'content-themes',\r\n");
      out.write("                'subtab-reviews': 'content-reviews'\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            Object.keys(subTabs).forEach(tabId => {\r\n");
      out.write("                document.getElementById(tabId).addEventListener('click', function() {\r\n");
      out.write("                    // 모든 서브탭 비활성화\r\n");
      out.write("                    Object.keys(subTabs).forEach(id => {\r\n");
      out.write("                        document.getElementById(id).classList.remove('subtab-active');\r\n");
      out.write("                        document.getElementById(id).classList.add('text-gray-600');\r\n");
      out.write("                        document.getElementById(subTabs[id]).classList.add('hidden');\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    // 선택한 서브탭 활성화\r\n");
      out.write("                    this.classList.add('subtab-active');\r\n");
      out.write("                    this.classList.remove('text-gray-600');\r\n");
      out.write("                    document.getElementById(subTabs[tabId]).classList.remove('hidden');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("<script>\r\n");
      out.write("    !function (t, e) { var o, n, p, r; e.__SV || (window.posthog = e, e._i = [], e.init = function (i, s, a) { function g(t, e) { var o = e.split(\".\"); 2 == o.length && (t = t[o[0]], e = o[1]), t[e] = function () { t.push([e].concat(Array.prototype.slice.call(arguments, 0))) } } (p = t.createElement(\"script\")).type = \"text/javascript\", p.crossOrigin = \"anonymous\", p.async = !0, p.src = s.api_host.replace(\".i.posthog.com\", \"-assets.i.posthog.com\") + \"/static/array.js\", (r = t.getElementsByTagName(\"script\")[0]).parentNode.insertBefore(p, r); var u = e; for (void 0 !== a ? u = e[a] = [] : a = \"posthog\", u.people = u.people || [], u.toString = function (t) { var e = \"posthog\"; return \"posthog\" !== a && (e += \".\" + a), t || (e += \" (stub)\"), e }, u.people.toString = function () { return u.toString(1) + \".people (stub)\" }, o = \"init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug\".split(\" \"), n = 0; n < o.length; n++)g(u, o[n]); e._i.push([i, s, a]) }, e.__SV = 1) }(document, window.posthog || []);\r\n");
      out.write("    posthog.init('phc_t9tkQZJiyi2ps9zUYm8TDsL6qXo4YmZx0Ot5rBlAlEd', {\r\n");
      out.write("        api_host: 'https://us.i.posthog.com',\r\n");
      out.write("        autocapture: false,\r\n");
      out.write("        capture_pageview: false,\r\n");
      out.write("        capture_pageleave: false,\r\n");
      out.write("        capture_performance: {\r\n");
      out.write("            web_vitals: false,\r\n");
      out.write("        },\r\n");
      out.write("        rageclick: false,\r\n");
      out.write("    })\r\n");
      out.write("    window.shareKey = 'vvu1-S91ByqFvJ6UrZFq-g';\r\n");
      out.write("    window.host = 'readdy.ai';\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://static.readdy.ai/static/share.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <div id=\"watermark\" class=\"group\" style=\"position: fixed; bottom: 48px; right: 46px; width: 184px; height: 39px; background-color: rgb(240, 240, 240); border-style: solid; border-width: 3px; border-radius: 12px; border-image-slice: 3; border-image-width: 3px; border-image-outset: 0; border-color: rgb(229, 231, 235); display: flex; align-items: center; justify-content: center; cursor: pointer;\"><div class=\"designed-by\" style=\"color: rgb(93, 93, 93); font-family: &quot;Secular One&quot;; font-size: 12px; line-height: 20px; font-weight: 400; padding-left: 12px;\">Designed by</div><img src=\"https://public.readdy.ai/gen_page/watermark.png\" style=\"width: 86px; margin-left: 0px;\"></div> -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
